### PR TITLE
Remote debugging feature

### PR DESCRIPTION
**Pull request by haydenjackson01**
#### Proposed changes
- Add a dialog before process selection to determine target machine for local or remote debugging.
- Change all dialogs to use floral-white as background for contrast with white textboxes and consistency.
- Update WMI/CIM query:
  * Allows for targeting of remote machines
  * Filter processes by name in query
- Remote processes will be debugged using the No AUTH transport layer.

#### Comments
Would be good to have someone else test this too, while *it works for me* I'm not exactly the target audience.

### CODE REVIEW

**Comment by haydenjackson01** [comment]
A new connection dialog is present before process selection, this determines where to route WMI/CIM commands. Other UIs are unchanged except for receiving the floral white background for consistency.

Connection dialog before process selection for local machine:
capture_connectionselector
The background is floral white to clarify that the textbox is uneditable in this state.

**Comment by haydenjackson01** [comment]
Connection dialog for unavailable machine:
capture_connectionselector_unavailablecomputer
Select button is disabled as the computer could not be pinged.

**Comment by haydenjackson01** [comment]
Connection dialog for available machine:
capture_connectionselector_availablecomputer

Visual Studio handles error when trying to attach to processes but no remote debugger is present.

**Comment by MarcinJuraszek** [comment]
1. I don't like the background. Why is it yellow?
2. It basically adds extra click to every single usage of the extension. Instead of having a new dialog that gates the existing one you should make it configurable from within the existing dialog, when needed, on a button click. The same way you can change debugging engine.

**Comment by haydenjackson01** [comment]
@MarcinJuraszek 
> 1. I don't like the background. Why is it yellow?

This was to add contrast to make a disabled textbox more apparent. I have fixed this to be more like: 
image

> 2. It basically adds extra click to every single usage of the extension. Instead of having a new dialog that gates the existing one you should make it configurable from within the existing dialog, when needed, on a button click. The same way you can change debugging engine.

Is something like below more preferable?
image

**Comment by MarcinJuraszek** [comment]
Yes! Assuming "Local Machine" is the default option.

**Review by MarcinJuraszek — APPROVED** [review]

**Comment by haydenjackson01** [comment]
Yes Local Machine, is default locked to the current computer.

**Pull request merged**
